email:
    noreply: noreply@gmap.com
    noreply_password: Hato1474
    helpdesk: helpdesk@gmap.com
    logerrors: DBAdmin@gmap.com


sql:
    server : 'tcp:afw4r24m.database.windows.net'  # SQL server name
    database : 'fordreporting_backend'  # database name
    username : 'User1'  # user ID
    password : 'asDFde345wnd'  # password, uses windows password

reports:
    GBRCarReport: '7c471772-39ac-4f5e-ace7-55496bd1416e'
    GBRCVReport: 'c4c20269-f06f-4fca-86c6-3abb64ec2943'
    IRLCarReport: '8c51c8a3-2b03-4c2e-9673-ceed4136ee2d'
    IRLCVReport: 'e930a88d-bf09-4274-8fd6-609c8d6e8d38'

ford:
    redirect_uri : 'https://azapp-ford-development.azurewebsites.net/auth'
    TOKEN_URL : 'https://corpqa.sts.ford.com/adfs/oauth2/token/'
    payload : 'grant_type=authorization_code&client_id=urn:dspd:clientid:dspd_web:dev&resource=urn:dspd:resource:dspd_web:dev&redirect_uri=https://azapp-ford-development.azurewebsites.net/auth&code='
    BASE_URL : 'https://corpqa.sts.ford.com/adfs/oauth2/authorize?response_type=code&client_id=urn:dspd:clientid:dspd_web:dev&resource=urn:dspd:resource:dspd_web:dev&redirect_uri=https://azapp-ford-development.azurewebsites.net/auth'
    # URL_Sitemk1: 'https://azapp-ford-edu.azurewebsites.net'
